version: '3.8'
services:
  jms:
    container_name: jms
    image: vromero/activemq-artemis
    ports:
      - '8161:8161'
      - '61616:61616'
  mysql:
    container_name: mysql
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    ports:
      - '3306:3306'
    volumes:
      - "./volumes/db_data:/var/lib/mysql"
  liresolr:
    container_name: liresolr
    image: dermotte/liresolr
    ports:
      - '8984:8983'
#    volumes:
#      - "./volumes/liresolr_data:/var/solr"
  solr:
    container_name: solr
    image: solr
    ports:
      - '8983:8983'
    volumes:
      - "./volumes/solr_data:/var/solr"
    command:
      - solr-precreate
      - gettingstarted
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
  filestoreservice:
    container_name: file-store-service
    image: johnwr/file-store-service
    environment:
      SPRING_PROFILES_ACTIVE: dockermysql
      SPRING_ARTEMIS_HOST: jms
    depends_on:
      - mysql
      - jms
  fileinfoservice:
    container_name: file-info-service
    image: johnwr/file-info-service
    ports:
      - '8071:8071'
    environment:
      SPRING_PROFILES_ACTIVE: dockermysql
    depends_on:
      - filestoreservice
      - mysql
  filewalkerservice:
    container_name: file-walker-service
    image: johnwr/file-walker-service
    volumes:
      - ./config/file-walker-service/fstab_6000-share:/etc/fstab
    environment:
      SPRING_PROFILES_ACTIVE: docker
#      RESPONSE_FILESTORE_OVERRIDE-WALK-PATH: /mnt/walkfolder/Test
      RESPONSE_SCHEDULING_FIXED-DELAY-TIME: PT1H
      RESPONSE_SCHEDULING_INITIAL-DELAY-TIME: PT20S
#      RESPONSE_FILEINFOSERVICE_HOST: http://fileinfoservice:8071
#      SPRING_ARTEMIS_HOST: jms
    privileged: true
    user: root
    depends_on:
      - jms
